auto:
	javac -d lib/bin lib/src/*.java
run:
	java -cp lib/bin lib/src/SingleFileCompression test/a.txt
	java -cp lib/bin lib/src/MultiFileCompression 'test/a.txt test/b.txt'
	java -cp lib/bin lib/src/DirectoryCompression test/
